### ISSUE TITLE
Security alert on several old packages

### ISSUE THREAD

**Issue by immartian** [Musicoin/website#16]
https://github.com/Musicoin/website/network/alerts

**Comment by immartian** [comment]
Hi @ehsanhajian and @riverfor, please consider merge into newest PR #15 by coordinating with @JoMo1970

**Comment by ehsanhajian** [comment]
maybe "npm audit fix" solve this issue

**Comment by riverfor** [comment]
I will have a look today, I am going to add the test mode for development.

**Comment by immartian** [comment]
fixed and closed.
